services:
  postgres:
    image: postgres:17.2-alpine
    container_name: weather_db
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: weather_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://weather_db:5432/weather_db
      SPRING_DATASOURCE_USERNAME: weather_user
      SPRING_DATASOURCE_PASSWORD: weather_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
